//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transaction_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debts
    {
        public int DebtID { get; set; }
        public int UserID { get; set; }
        public string PersonName { get; set; }
        public decimal Amount { get; set; }
        public string DebtType { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public string Note { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
