//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transaction_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Savings
    {
        public int SavingID { get; set; }
        public int UserID { get; set; }
        public string GoalName { get; set; }
        public decimal TargetAmount { get; set; }
        public Nullable<decimal> CurrentAmount { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string Status { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
