//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transaction_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions
    {
        public int TransactionID { get; set; }
        public int UserID { get; set; }
        public int WalletID { get; set; }
        public int CategoryID { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string Note { get; set; }
        public string ReceiptImage { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Users Users { get; set; }
        public virtual Wallets Wallets { get; set; }
    }
}
