//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transaction_Management.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TMDatabase : DbContext
    {
        public TMDatabase()
            : base("name=TMDatabase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Budgets> Budgets { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Debts> Debts { get; set; }
        public virtual DbSet<RecurringBills> RecurringBills { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Savings> Savings { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Transactions> Transactions { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Wallets> Wallets { get; set; }
    }
}
